### PR TITLE
i18n: support i18n shortcut

### PR DESCRIPTION
**Pull request by shigma**

### CODE REVIEW

**Comment by MaikoTan** [comment]
Shall you rebase this PR to the updated main branch?

**Comment by shigma** [comment]
This feature is not an urgent one. I'd like to wait until the other PRs are merged.

**Comment by MaikoTan** [comment]
> This feature is not an urgent one. I'd like to wait until the other PRs are merged.

Well, I just worried that you have sensitive information left in this branch that triggered DMCA before.

**Comment by shigma** [comment]
superseded by e0474488b4472669a1826f7f3157be394ac02d8a.

**Pull request closed without merging**
