### PR TITLE
fix: libsodium import error with sumo version

### LINKED ISSUE #181: Bug: 发生未知错误，沙盒测试无法通过
### Describe the bug

沙盒测试输入nai指令有正确回应help列表，但是加上tag会出现未知错误。

### Steps to reproduce

已更新koishi到最新的4.11.9，novelAI插件版本为1.17.3，沙盒测试输入nai或其他对应指令有回应help列表。
但是加上tag后沙盒测试显示发生未知错误，中间也没有显示正在作画。

### Expected behavior

已经重装novel插件，依然无法解决问题。

### Screenshots

[image](https://user-images.githubusercontent.com/127010181/222947535-3a230d6f-1359-48f5-ae4e-9d8f521dcd30.png)

### Relevant log output

```shell
2023-03-05 15:06:31 [E] novelai TypeError: hash_length cannot be null or undefined
at f (C:\Users\Administrator\AppData\Roaming\Koishi\(Desktop(data\instances (default\node_modules\libsodium-
wrappersldist\modules\libsodium-wrappers.js:1:17851)
at m (Cc:\Users Administrator\AppData \Roaming\Koishi\Desktop\data\instances\default\(node_modules \libsodium-
wrappers \dist\modules\libsodium-wrappers.js:1:17895)
at Xe (C:\Users \Administrator \AppData \Roaming\Koishi\Desktop\data\instances\default\node_modules libsodium-
wrappers \dist\modules\libsodium-wrappers.js :1:49004)
at calcAccessKey
(c:\Users \Administrator \AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules
\koishi-plugin-novelai\lib\utils.js:61: 139)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async login
(C: \Users \Administrator\AppData\Roaming(Koishi\Desktop\data\instances\default\node_modules
koishi-plugin-novelai\lib\utils.js :98:18)
at async _Command.<anonymous>
(C: \Users \Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules
\koishi-plugin-novelai\lib\index.js:172:21)
at async Array.<anonymous>
(C: \Users\Administrator'ApData Roaming Koishi\Desktop\dataNinstances 'default(node modules(koishijs core\lib\index.cjs:1653:14)
```

### Launcher

Koishi Desktop

### Backend

NovelAI (帐号密码)

### Versions

- OS: <-- WindowsServer 2022 -->
- Koishi version: 

### Additional context

_No response_

### LINKED ISSUE #196: Bug: novelai TypeError: hash_length cannot be null or undefined
### Describe the bug

在沙盒中测试报错
image
image

### Steps to reproduce

image

### Expected behavior

能正常使用该插件

### Screenshots

_No response_

### Relevant log output

_No response_

### Launcher

Koishi Desktop

### Backend

NovelAI (帐号密码)

### Versions

System:
    OS: Linux 5.4 Alpine Linux
    CPU: (2) x64 AMD EPYC 7K62 48-Core Processor

Binaries:
    Node: 18.15.0
    Yarn: 1.22.19

Koishi:
    Core: 4.12.6
    Console: 5.6.2

koishi-plugin-novelai | 1.17.4 (最新)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaikoTan**
fix #181
fix #196

### CODE REVIEW

**Comment by MaikoTan** [comment]
Need people with NovelAI account to test this PR before merging it.

**Comment by KouyouMomiji** [comment]
how?

**Comment by MaikoTan** [comment]
> how?

Assuming you are using the [`koishi-boilerplate`](https://github.com/koishijs/boilerplate) as the development environment:

1. Clone `novelai-bot` repo locally:

```bash
$ git clone https://github.com/koishijs/novelai-bot.git ./external/novelai-bot
```

2. Set branch to the current PR

```bash
$ git -C ./external/novelai-bot checkout fix/use-libsodium-sumo
```

3. Install dependencies and build

```bash
$ yarn && yarn build
```

4. Run Koishi in development mode

```bash
$ yarn dev
```

You can learn more in [Koishi Official Website](https://koishi.chat/zh-CN/guide/develop/workspace.html)

**Comment by KouyouMomiji** [comment]
2023-04-12 21:06:58 [I] app apply plugin novelai:3el8u1
2023-04-12 21:06:58 [E] app cannot resolve plugin "novelai

**Comment by lin-strive** [comment]
sorry 怎么继续修复

**Comment by lin-strive** [comment]
image

**Comment by lin-strive** [comment]
image

**Review by shigma — APPROVED** [review]

**Pull request merged**
