### PR TITLE
feat: add face restoration for sd-webui

### LINKED ISSUE #142: Feature: Face Restoration in SD-WebUI
### Scope

Stable Diffusion WebUI (AUTOMATIC1111)

### Describe the problem related to the feature request

Implement "Face Restoration" feature in txt2img mode.

### Describe the solution you'd like

- Add a new configuration says `face restoration`, values are `Off`, `CodeFormer` and `GFPGAN` that respect the backend.
- Add a new configuration says `face restoration strength` that controls the strength of face restoration mentioned above. (values: 0.0 - 1.0)
- Before sending a request, add `restore_face` property as values above.

### Describe alternatives you've considered

None.

### Additional context

Only SD-WebUI support face restoration.

### PR DESCRIPTION
**Pull request by MaikoTan**
close #142 

This PR should be merged after #154 because conflict.

### CODE REVIEW

**Comment by shigma** [comment]
To avoid conflict I recommend you just put things together.

**Comment by MaikoTan** [comment]
> To avoid conflict I recommend you just put things together.

They are different things so I think it is not good to put them together.

**Comment by shigma** [comment]
> > To avoid conflict I recommend you just put things together.
> 
> They are different things so I think it is not good to put them together.

image

But you did put them together. I suggest so because I saw the code.

**Comment by MaikoTan** [comment]
> > > To avoid conflict I recommend you just put things together.
> > 
> > They are different things so I think it is not good to put them together.
> 
> image
> 
> But you did put them together. I suggest so because I saw the code.
> 

Oh, that's a mistake. Sumimasen !

**Review by shigma — APPROVED** [review]
善

**Comment by MaikoTan** [comment]
> 善

What is the meaning of 善?

**Comment by shigma** [comment]
> What is the meaning of 善?

Good. = LGTM

**Comment by MaikoTan** [comment]
> Good. = LGTM

Good.

**Pull request merged**
