### PR TITLE
fix: sd-webui sampler index error cause 422

### PR DESCRIPTION
**Pull request by MaikoTan**

### CODE REVIEW

**Comment by MaikoTan** [comment]
Samplers only `Euler a`, `Euler`, `LMS`, `PLMS`, and `DDIM` are listed, which behaves as same as novelai.net currently.
只列出了`Euler a`、`Euler`、`LMS`、`PLMS`和`DDIM`等采样器，其行为与novelai.net目前相同。

**Comment by shigma** [comment]
Actually you can calculate the `type` based on `config` using the `ctx.accept()` API.

**Comment by MaikoTan** [comment]
> Actually you can calculate the `type` based on `config` using the `ctx.accept()` API.

I don't get your point. How to use this API?

**Comment by shigma** [comment]
https://github.com/koishijs/novelai-bot/blob/b867428d6c38ec71dc7115ab7bd428427f09fc3f/src/index.ts#L447-L451

https://github.com/koishijs/novelai-bot/blob/b867428d6c38ec71dc7115ab7bd428427f09fc3f/src/index.ts#L199

I can work on this if you don't know what to do.

**Comment by MaikoTan** [comment]
Yeah, I saw the example code but still not got the point.
Sorry, but may I ask you to continue to work on this PR?

**Review by shigma — APPROVED** [review]

**Pull request merged**
